### ISSUE TITLE
Hibernate 6.4.0 breaks hibernate-batch-sequence-generator due to removal of ResultSetReturn.extract(Statement)

### ISSUE THREAD

**Issue by mmusenbr** [marschall/hibernate-batch-sequence-generator#15]
In commit https://github.com/hibernate/hibernate-orm/commit/d27cc1043839cc62ee29cc4b5d59519cc0d70c9f the deprecated `ResultSetReturn.extract(Statement)` method was removed.
I could not find any references in the release note/migration guide for that.

It looks like `ResultSet ResultSetReturn.extract(PreparedStatement statement, String sql);` is the one to use, but I am not sure in this case what to pass as `sql`, otherwise I would have added a patch.

br

**Comment by marschall** [comment]
Thanks for reporting. Your analysis is spot on. I created 2.1.1 with the fix.

(2.1.0 did not make it into Maven Central due to missing javadocs)
