### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bukajsytlos** [marschall/hibernate-batch-sequence-generator#3]
Hello.
Could you please update license info?
Can I take your code and adapt it to older hibernate?
Thank you

**Comment by marschall** [comment]
The license of the project is MIT as declared in the POM
https://github.com/marschall/hibernate-batch-sequence-generator/blob/master/pom.xml#L28
unfortunately GitHub does not pick that up.
I also added a license file under `src/main/resources` https://github.com/marschall/hibernate-batch-sequence-generator/tree/master/src/main/resources but GitHub does not pick that up either.

> Can I take your code and adapt it to older hibernate?

Sure

**Comment by bukajsytlos** [comment]
Ah didn't notice. Thank you very much for this.
