### ISSUE TITLE
Would you like to add an OSS license to it?

### ISSUE THREAD

**Issue by vladmihalcea** [marschall/hibernate-batch-sequence-generator#5]
I'm now writing an article about the Hibernate Beach Sequence Generator and realized there's no license in the project. In the absence of an OSS license,e it means the code is copyrighted and no one is allowed to use the library unless you grant them access.

Alternatively, would you like to integrate it into [Hibernate Types](https://github.com/vladmihalcea/hibernate-types) and make it available automatically to hundreds of thousand of Java devs? Thanks.

**Comment by marschall** [comment]
Thank you for your interest in my project. The project is MIT licensed, the license is listed in the POM and a license file is included in the JAR. I can see two reasons why confusion may arise:

- GitHub did not pick up the license even though it is checked in and they parse the POM. GitHub only seems to pick up license files in the project root, not in \`src/main/resources`. Moving the file to the root is a bit annoying as it goes against Maven conventions and requires additional configuration in the POM. I fixed this in d33d47ac5e5ade632562540ae84e024d7788d14a.
- The source file does not have a license header. It is my understanding that this is not required. Let me know if you disagree and I will add a license header as well.

Integration into [Hibernate Types](https://github.com/vladmihalcea/hibernate-types) would be fantastic. I'll open an issue there so we can proceed further.

**Comment by vladmihalcea** [comment]
Thanks for the info. Looking forward to your Pull Request in the Hibernate Types project. I've added other utilities over the years, so it will be great to include the Batch Sequence Generator.

I've already published [an article about it](https://vladmihalcea.com/hibernate-batch-sequence-generator/).
